language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install: ./.travis.gpg.sh

deploy:
  provider: script
  script: echo $GPG_PASSPHRASE && mvn --settings .travis.settings.xml clean deploy
  skip_cleanup: true
