language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install: source .travis.gpg.sh

deploy:
  provider: script
  script: mvn --settings .travis.settings.xml clean deploy
  skip_cleanup: true
